vars:
  "Edeposited"            : [100, 0, 1000]
  "totalInitialE"         : [100, 0, 20000]
  "totalMCPulseCharge"    : [100, 0, 4000]
  "totalDOMHits"          : [100, 0, 2500]


# -- hist configurations
attri:
  "colorblind"             : [ "#003f5c", "#bc5090", "#ffa600", "#ff6361", "#000000", "#444444", "#888888", "#cccccc", "#e6e6e6",
                              "#f5f5f5", "#ffffff", "#56b4e9", "#009e73", "#f0e442"]

