#still work in progress -- eventually want to port over all vars and mods to a yaml for plotting config

---
sig: 
  DLS : DarkLeptonicScalar*
  # DLS No LLP : NO_LLP*

"bins" = 100
vars:
-  "Edeposited"            : [100, 0, 1000]
-  "totalInitialE"         : [100, 0, 20000]
-  "totalMCPulseCharge"    : [100, 0, 4000]
-  "totalDOMHits"          : [100, 0, 2500]

